=== JohnSire/zoe-phip/zoe-phip/2.module/phip-module-service-impl/src/main/resources/multicacheschemas/ProvideAndRegisterDocumentSetRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (http://www.altova.com) by wangxien (wangxien) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:xs="urn:hl7-org:v3" targetNamespace="urn:hl7-org:v3" elementFormDefault="qualified">
	<element name="ProvideAndRegisterDocumentSetRequest">
		<complexType>
			<sequence>
				<element minOccurs="0" name="ID" type="xs:II">
					<annotation>
						<documentation>消息标识</documentation>
					</annotation>
				</element>
				<element name="SourcePatientID" type="s:string" minOccurs="0">
					<annotation>
						<documentation>患者标识</documentation>
					</annotation>
				</element>
				<element name="SourcePatientName" type="s:string">
					<annotation>
						<documentation>患者姓名</documentation>
					</annotation>
				</element>
				<element name="HealthCardId" type="s:string" minOccurs="0">
					<annotation>
						<documentation>患者健康卡号</documentation>
					</annotation>
				</element>
				<element name="IdentityId" type="s:string">
					<annotation>
						<documentation>患者身份证号</documentation>
					</annotation>
				</element>
				<element name="Organization" type="xs:Organization" nillable="true" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>健康机构信息</documentation>
					</annotation>
				</element>
				<element name="RegistryPackage" type="xs:RegistryPackage">
					<annotation>
						<documentation>共享文档注册条目包</documentation>
					</annotation>
				</element>
				<element name="Document" type="xs:DocumentEntry" maxOccurs="unbounded">
					<annotation>
						<documentation>提交共享文档内容</documentation>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>
	<complexType name="II">
		<attribute name="root" type="s:string">
			<annotation>
				<documentation>标识符根</documentation>
			</annotation>
		</attribute>
		<attribute name="extension" type="s:string">
			<annotation>
				<documentation>根下唯一标识</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="Organization">
		<sequence>
			<element name="Name" type="s:string" minOccurs="0">
				<annotation>
					<documentation>名称</documentation>
				</annotation>
			</element>
			<element name="TelephoneNumber" type="xs:Telephone" minOccurs="0">
				<annotation>
					<documentation>联系电话</documentation>
				</annotation>
			</element>
			<element name="EmailAddress" type="xs:Email" minOccurs="0">
				<annotation>
					<documentation>电子邮件</documentation>
				</annotation>
			</element>
			<element name="Address" type="xs:Address" minOccurs="0">
				<annotation>
					<documentation>联系地址</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="s:string">
			<annotation>
				<documentation>机构组织代码</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="Telephone">
		<attribute name="areaCode" type="s:string">
			<annotation>
				<documentation>区号</documentation>
			</annotation>
		</attribute>
		<attribute name="countryCode" type="s:string">
			<annotation>
				<documentation>国家号</documentation>
			</annotation>
		</attribute>
		<attribute name="extension" type="s:string">
			<annotation>
				<documentation>后缀</documentation>
			</annotation>
		</attribute>
		<attribute name="number" type="s:string">
			<annotation>
				<documentation>号码</documentation>
			</annotation>
		</attribute>
		<attribute name="phoneType" type="s:string">
			<annotation>
				<documentation>电话类型</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="Email">
		<attribute name="address" type="s:string">
			<annotation>
				<documentation>邮件地址</documentation>
			</annotation>
		</attribute>
		<attribute name="type" type="s:string">
			<annotation>
				<documentation>类型</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="Address">
		<attribute name="city" type="s:string">
			<annotation>
				<documentation>城市</documentation>
			</annotation>
		</attribute>
		<attribute name="country" type="s:string">
			<annotation>
				<documentation>国家</documentation>
			</annotation>
		</attribute>
		<attribute name="postalCode" type="s:string">
			<annotation>
				<documentation>邮政编码</documentation>
			</annotation>
		</attribute>
		<attribute name="stateOrProvince" type="s:string">
			<annotation>
				<documentation>州、省</documentation>
			</annotation>
		</attribute>
		<attribute name="street" type="s:string">
			<annotation>
				<documentation>街道</documentation>
			</annotation>
		</attribute>
		<attribute name="streetNumber" type="s:string">
			<annotation>
				<documentation>街道号码</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="RegistryPackage">
		<sequence>
			<element name="SubmissionSet" type="xs:SubmissionSet" maxOccurs="unbounded">
				<annotation>
					<documentation>共享文档提交集信息</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SubmissionSet">
		<sequence>
			<element name="ContentTypeCode" type="s:string" minOccurs="0">
				<annotation>
					<documentation>共享文档内容类型代码</documentation>
				</annotation>
			</element>
			<element name="ContentTypeCodeDisplayName" type="s:string" minOccurs="0">
				<annotation>
					<documentation>共享文档内容类型代码名称</documentation>
				</annotation>
			</element>
			<element name="SubmissionTime" type="s:dateTime" minOccurs="0">
				<annotation>
					<documentation>提交时间</documentation>
				</annotation>
			</element>
			<element name="UniqueId" type="s:string" minOccurs="0">
				<annotation>
					<documentation>提交集唯一标识符</documentation>
				</annotation>
			</element>
			<element name="SourceId" type="s:string" minOccurs="0">
				<annotation>
					<documentation>贡献提交集的唯一标识符</documentation>
				</annotation>
			</element>
			<element name="PatientID" type="s:string" minOccurs="0">
				<annotation>
					<documentation>外部患者唯一标识符</documentation>
				</annotation>
			</element>
			<element name="Comments" type="s:string" minOccurs="0">
				<annotation>
					<documentation>提交集对共享文档描述</documentation>
				</annotation>
			</element>
			<element name="Title" type="s:string" minOccurs="0">
				<annotation>
					<documentation>共享文档标题</documentation>
				</annotation>
			</element>
			<element name="CreateTime" type="s:dateTime" minOccurs="0">
				<annotation>
					<documentation>共享文档创建时间</documentation>
				</annotation>
			</element>
			<element name="ServerOrganization" type="s:string" minOccurs="0">
				<annotation>
					<documentation>就诊机构名称</documentation>
				</annotation>
			</element>
			<element name="EpisodeID" type="s:string" minOccurs="0">
				<annotation>
					<documentation>就诊号</documentation>
				</annotation>
			</element>
			<element name="InTime" type="s:dateTime" minOccurs="0">
				<annotation>
					<documentation>入院时间</documentation>
				</annotation>
			</element>
			<element name="OutTime" type="s:dateTime" minOccurs="0">
				<annotation>
					<documentation>出院时间</documentation>
				</annotation>
			</element>
			<element name="AdmissionDepart" type="s:string" minOccurs="0">
				<annotation>
					<documentation>就诊科室</documentation>
				</annotation>
			</element>
			<element name="AdmissionDoctor" type="s:string" minOccurs="0">
				<annotation>
					<documentation>主管医生</documentation>
				</annotation>
			</element>
			<element name="AdmissionType" type="s:string" minOccurs="0">
				<annotation>
					<documentation>就诊类型</documentation>
				</annotation>
			</element>
			<element name="DiagnosisResult" type="s:string" minOccurs="0">
				<annotation>
					<documentation>诊断</documentation>
				</annotation>
			</element>
			<element name="Author" type="xs:Author" nillable="true" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>共享文档作者信息</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="targetObject" type="s:string">
			<annotation>
				<documentation>所关联共享文档</documentation>
			</annotation>
		</attribute>
		<attribute name="availabilityStatus" type="s:string">
			<annotation>
				<documentation>文档可用状态,取值为:Submitted;Approved</documentation>
			</annotation>
		</attribute>
	</complexType>
	<complexType name="ArrayOfAuthorAuthor">
		<sequence>
			<element name="Author" type="xs:Author" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="Author">
		<sequence>
			<element name="AuthorName" type="s:string">
				<annotation>
					<documentation>共享文档作者</documentation>
				</annotation>
			</element>
			<element name="AuthorInstitution" type="s:string" minOccurs="0">
				<annotation>
					<documentation>共享文档作者所在机构</documentation>
				</annotation>
			</element>
			<element name="AuthorSpecialty" type="s:string" minOccurs="0">
				<annotation>
					<documentation>共享文档作者专业</documentation>
				</annotation>
			</element>
			<element name="AuthorRole" type="s:string" minOccurs="0">
				<annotation>
					<documentation>共享文档作者角色信息</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="DocumentEntry">
		<sequence>
			<element name="Content" type="s:base64Binary" minOccurs="0">
				<annotation>
					<documentation>共享文档内容</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="id" type="s:string">
			<annotation>
				<documentation>文档唯一标识符</documentation>
			</annotation>
		</attribute>
		<attribute name="mimeType" type="s:string">
			<annotation>
				<documentation>文档格式</documentation>
			</annotation>
		</attribute>
		<attribute name="parentDocumentRelationship" type="s:string">
			<annotation>
				<documentation>与父文档关系类别</documentation>
			</annotation>
		</attribute>
		<attribute name="parentDocumentId" type="s:string">
			<annotation>
				<documentation>父文档唯一标识号</documentation>
			</annotation>
		</attribute>
	</complexType>
</schema>

=== JohnSire/zoe-phip/zoe-phip/2.module/phip-repository/phip-repository-service-impl/src/main/resources/template/document/input/EHR-PL-13健康档案文档注册-T01.xml
<ProvideAndRegisterDocumentSetRequest xmlns="urn:hl7-org:v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:schemaLocation="urn:hl7-org:v3 ../multicacheschemas/ProvideAndRegisterDocumentSetRequest.xsd">
    <ID root="2.16.156.10011.0" extension="C193FE3B-E71F-4D81-8B8B-9462F35E8D38"/>
    <SourcePatientID>201507287435</SourcePatientID>
    <SourcePatientName>李云发</SourcePatientName>
    <HealthCardId>000000201507287435</HealthCardId>
    <IdentityId>350825201507287435</IdentityId>
    <Organization id="022103A005">
        <Name>厦门大学附属第一医院</Name>
        <TelephoneNumber areaCode="022" number="4448888"/>
        <EmailAddress address="XXX@yy.com.cn"/>
        <Address city="思明区" country="中国" postalCode="300002" stateOrProvince="厦门市"
                 street="云顶路" streetNumber="1234"/>
    </Organization>
    <RegistryPackage>
        <SubmissionSet targetObject="Document.1" availabilityStatus="Submitted">
            <SubmissionTime>2015-07-29T02:00:01Z</SubmissionTime>
            <UniqueId>1234567890</UniqueId>
            <SourceId>367098466511</SourceId>
            <Comments>脑缺血</Comments>
            <Title>门诊摘要</Title>
            <CreateTime>2015-07-29T03:27:29Z</CreateTime>
            <ServerOrganization>厦门大学附属第一医院</ServerOrganization>
            <EpisodeID>0201507287435</EpisodeID>
            <InTime>2015-07-28T10:43:15Z</InTime>
            <OutTime>2015-07-28T11:31:23Z</OutTime>
            <AdmissionDepart>内科</AdmissionDepart>
            <AdmissionDoctor>赵俊立1</AdmissionDoctor>
            <AdmissionType>门诊</AdmissionType>
            <DiagnosisResult>脑缺血</DiagnosisResult>
            <Author>
                <AuthorName>赵俊立</AuthorName>
                <AuthorInstitution>厦门大学附属第一医院</AuthorInstitution>
                <AuthorSpecialty>内科</AuthorSpecialty>
                <AuthorRole>三级专家</AuthorRole>
            </Author>
        </SubmissionSet>
    </RegistryPackage>
    <Document id="12345678" mimeType="text/xml" parentDocumentRelationship="APND"
              parentDocumentId="AAC97D6B-75BC-4E6E-8174-EFC09C722A09">
        <Content>
            PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iZ2IyMzEyIj8+PHJvb3QgdGltZT0iMjAxNS0wNy0yOSAwMDowMDowMCI+PG9yZz48aXRlbSBvcmdjb2RlPSIzNTAyMTFBMTAwMSIgb3JnbmFtZT0iz8PDxbTz0ae4vcr0tdrSu9K91LoiIC8+PC9vcmc+PGFjdGl2ZXBhdGllbnQ+PGl0ZW0gZGF0ZXRpbWU9IjIwMTUtMDctMjkgMTY6MzA6MzAiIG9yZ2NvZGU9IjM1MDIxMUExMDAxIiBvcmduYW1lPSLPw8PFtPPRp7i9yvS12tK70r3UuiIgY2FyZF9ubz0iMjAxNTA3Mjg3NDM1IiBuYW1lPSLA7tTGt6IiIHNleF9jb2RlPSIxIiBzZXhfbmFtZT0ixNDQ1CIgYmlydGhfZGF0ZT0iIiBsYXN0X3VwZGF0ZV9kdGltZT0iMjAxNS83LzI5IDI6MDA6MDEiIG9yZ19jb2RlPSIzNTAyMTFBMTAwMSIgcGF0aWVudF9pZD0iMjAxNTA3Mjg3NDM1IiBldmVudF90eXBlPSIxIiBldmVudF9ubz0iMjAxNTA3Mjg3NDM1IiByZXRyaWV2ZV9kYXRlPSIyMDE1LzcvMjkgMjowMDowMSIgc3RhcnRfZGF0ZT0iMjAxNS83LzI4IDEwOjQzOjE1IiBlbmRfZGF0ZT0iMjAxNS83LzI4IDExOjMxOjIzIiBmZWU9IjM4MC4wMCIgaWNkPSIgIiBkaWFnbm9zaXM9IsTUyLHRqiIgYWRkcmVzc19jb2RlPSIiIGFkZHJlc3M9IiIgdGVsX25vPSIiIG1hcnJpYWdlX2NvZGU9IiIgbWFycmlhZ2VfbmFtZT0iIiBvbnNldF9kdGltZT0iIiBkaWFnbm9zaXNfZGF0ZT0iMjAxNS83LzI4IDEwOjQzOjE1IiBjcmVhdGVfdGltZT0iMjAxNS83LzI5IDM6MDI6MDkiIC8+PC9hY3RpdmVwYXRpZW50PjxwYXRpZW50PjxpdGVtIGxhc3RfdXBkYXRlX2R0aW1lPSIyMDE1LzcvMjkgMjowMDowMSIgb3JnX2NvZGU9IjM1MDIxMUExMDAxIiBwYXRpZW50X2lkPSIyMDE1MDcyODc0MzUiIG91dHBhdF9mb3JtX25vPSIyMDE1MDcyODc0MzUiIGhlYWx0aF9yZWNvcmRfbm89IiIgbmFtZT0iwO7UxreiIiBzZXhfY29kZT0iMSIgc2V4X25hbWU9IsTQ0NQiIGJpcnRoX2RhdGU9IiIgbWFycmlhZ2VfY29kZT0iIiBtYXJyaWFnZV9uYW1lPSIiIGlkX3R5cGVfY29kZT0iOTkiIGlkX3R5cGVfbmFtZT0ivtPD8cntt93WpCIgaWRfbm89IjIwMTUwNzI4NzQzNSIgdmlzaXRfb3JnX25hbWU9Is/Dw8W089GnuL3K9LXa0rvSvdS6IiB2aXNpdF9vcmdfY29kZT0iNDAxMzU0MzEiIHZpc2l0X2RlcHRfbmFtZT0ixNq/xiIgdmlzaXRfZHRpbWU9IjIwMTUvNy8yOCAxMTozMToyMyIgcmVmZXJyYWxfbWFyaz0iIiByZWZlcnJhbF9tYXJrX25hbWU9IiIgY29uc3VsdF9xdWVzdGlvbj0iIiBoZWFsdGhfc2VydmljZV9kZW1hbmQ9IiIgaGVhbHRoX3Byb2JsZW1fZXZhbD0iIiB0cmVhdG1lbnRfcGxhbj0iIiBvdGhlcl9tZWRpY2FsX3RyZWF0bWVudD0iIiByZXNwX2RvY3Rvcl9uYW1lPSLV1L+hwaIiIHNicD0iIiBkYnA9IiIgY3JlYXRlX3RpbWU9IjIwMTUvNy8yOSAzOjI3OjI5IiByZWdfY29kZT0iMjAxNTA3Mjg3NDM1IiAvPjwvcGF0aWVudD48c3ltcHRvbSAvPjx0ZXN0IC8+PGRpYWdub3Npcz48aXRlbSBsYXN0X3VwZGF0ZV9kdGltZT0iMjAxNS83LzI5IDI6MDA6MDEiIG9yZ19jb2RlPSIzNTAyMTFBMTAwMSIgb3V0cGF0X2Zvcm1fbm89IjIwMTUwNzI4NzQzNSIgb3V0cGF0X2RpYWdfbmFtZT0ixNTIsdGqIiBvdXRwYXRfZGlhZ19jb2RlPSIgIiBkaWFnX2RhdGU9IjIwMTUvNy8yOCAxMTozMToyMyIgZGlhZ25vc2lzX2lkPSIxIiBjcmVhdGVfdGltZT0iMjAxNS83LzI5IDM6Mjc6NTkiIC8+PC9kaWFnbm9zaXM+PGRydWcgLz48ZmVlPjxpdGVtIGxhc3RfdXBkYXRlX2R0aW1lPSIyMDE1LzcvMjkgMjowMDowMSIgb3JnX2NvZGU9IjM1MDIxMUExMDAxIiBvdXRwYXRfZm9ybV9ubz0iMjAxNTA3Mjg3NDM1IiBvdXRwYXRfZmVlX3R5cGVfY29kZT0iMDQiIG91dHBhdF9mZWVfdHlwZV9uYW1lPSK87LLpt9EiIG91dHBhdF9mZWVfYW1vdW50PSIxMjAuMDAiIHBheV93YXlfY29kZT0iOTkiIHBheV93YXlfbmFtZT0ixuTL+yIgb3V0cGF0X3NldHRsZV93YXlfY29kZT0iMDEiIG91dHBhdF9zZXR0bGVfd2F5X25hbWU9Is/WvfAiIHByaWNlX2l0ZW1fbG9jYWxfbmFtZT0ivq3CrbbgxtXA1SIgcHJpY2VfaXRlbV9sb2NhbF9jb2RlPSIwMDgwMDAxMSIgcHJpY2VfaXRlbV9zdGRfbmFtZT0ivq3CrbbgxtXA1SIgcHJpY2VfaXRlbV9zdGRfY29kZT0iMDAyODc4IiBpZD0iY3oxMzA3NDA5OCIgY3JlYXRlX3RpbWU9IjIwMTUvNy8yOSAzOjMwOjQ2IiAvPjxpdGVtIGxhc3RfdXBkYXRlX2R0aW1lPSIyMDE1LzcvMjkgMjowMDowMSIgb3JnX2NvZGU9IjM1MDIxMUExMDAxIiBvdXRwYXRfZm9ybV9ubz0iMjAxNTA3Mjg3NDM1IiBvdXRwYXRfZmVlX3R5cGVfY29kZT0iMDQiIG91dHBhdF9mZWVfdHlwZV9uYW1lPSK87LLpt9EiIG91dHBhdF9mZWVfYW1vdW50PSIxMzAuMDAiIHBheV93YXlfY29kZT0iOTkiIHBheV93YXlfbmFtZT0ixuTL+yIgb3V0cGF0X3NldHRsZV93YXlfY29kZT0iMDEiIG91dHBhdF9zZXR0bGVfd2F5X25hbWU9Is/WvfAiIHByaWNlX2l0ZW1fbG9jYWxfbmFtZT0ivrGyv9GqudyyysmrtuDG1cDVs6zJ+cG9uPnRqrncIiBwcmljZV9pdGVtX2xvY2FsX2NvZGU9IjAwODAwMDQ3IiBwcmljZV9pdGVtX3N0ZF9uYW1lPSK+sbK/0aq53LLKyau24MbVwNazrMn5IiBwcmljZV9pdGVtX3N0ZF9jb2RlPSIyMDgxMDQiIGlkPSJjejEzMDc0MDk5IiBjcmVhdGVfdGltZT0iMjAxNS83LzI5IDM6MzA6NDYiIC8+PGl0ZW0gbGFzdF91cGRhdGVfZHRpbWU9IjIwMTUvNy8yOSAyOjAwOjAxIiBvcmdfY29kZT0iMzUwMjExQTEwMDEiIG91dHBhdF9mb3JtX25vPSIyMDE1MDcyODc0MzUiIG91dHBhdF9mZWVfdHlwZV9jb2RlPSIwNCIgb3V0cGF0X2ZlZV90eXBlX25hbWU9Irzssum30SIgb3V0cGF0X2ZlZV9hbW91bnQ9IjcwLjAwIiBwYXlfd2F5X2NvZGU9Ijk5IiBwYXlfd2F5X25hbWU9Isbky/siIG91dHBhdF9zZXR0bGVfd2F5X2NvZGU9IjAxIiBvdXRwYXRfc2V0dGxlX3dheV9uYW1lPSLP1r3wIiBwcmljZV9pdGVtX2xvY2FsX25hbWU9Ir6xsr/RqrncssrJq7bgxtXA1bOsyfnU9rzTwb24+SIgcHJpY2VfaXRlbV9sb2NhbF9jb2RlPSIwMDgwMDA0OCIgcHJpY2VfaXRlbV9zdGRfbmFtZT0ivrGyv9GqudyyysmrtuDG1cDWs6zJ+aOow7/U9rzTMrj5vNPK1aPAIiBwcmljZV9pdGVtX3N0ZF9jb2RlPSIyMDgxMDUiIGlkPSJjejEzMDc0MTAwIiBjcmVhdGVfdGltZT0iMjAxNS83LzI5IDM6MzA6NDYiIC8+PGl0ZW0gbGFzdF91cGRhdGVfZHRpbWU9IjIwMTUvNy8yOSAyOjAwOjAxIiBvcmdfY29kZT0iMzUwMjExQTEwMDEiIG91dHBhdF9mb3JtX25vPSIyMDE1MDcyODc0MzUiIG91dHBhdF9mZWVfdHlwZV9jb2RlPSIxNCIgb3V0cGF0X2ZlZV90eXBlX25hbWU9IrLEwc+30SIgb3V0cGF0X2ZlZV9hbW91bnQ9IjQwLjAwIiBwYXlfd2F5X2NvZGU9Ijk5IiBwYXlfd2F5X25hbWU9Isbky/siIG91dHBhdF9zZXR0bGVfd2F5X2NvZGU9IjAxIiBvdXRwYXRfc2V0dGxlX3dheV9uYW1lPSLP1r3wIiBwcmljZV9pdGVtX2xvY2FsX25hbWU9IrLKyavN0MCtxqwiIHByaWNlX2l0ZW1fbG9jYWxfY29kZT0iMDE4MDA0NDciIHByaWNlX2l0ZW1fc3RkX25hbWU9IrLKyavN0MCtxqwiIHByaWNlX2l0ZW1fc3RkX2NvZGU9IjIwNzU0OCIgaWQ9ImN6MTMwNzQxMDEiIGNyZWF0ZV90aW1lPSIyMDE1LzcvMjkgMzozMDo0NiIgLz48aXRlbSBsYXN0X3VwZGF0ZV9kdGltZT0iMjAxNS83LzI5IDI6MDA6MDEiIG9yZ19jb2RlPSIzNTAyMTFBMTAwMSIgb3V0cGF0X2Zvcm1fbm89IjIwMTUwNzI4NzQzNSIgb3V0cGF0X2ZlZV90eXBlX2NvZGU9IjE0IiBvdXRwYXRfZmVlX3R5cGVfbmFtZT0issTBz7fRIiBvdXRwYXRfZmVlX2Ftb3VudD0iMjAuMDAiIHBheV93YXlfY29kZT0iOTkiIHBheV93YXlfbmFtZT0ixuTL+yIgb3V0cGF0X3NldHRsZV93YXlfY29kZT0iMDEiIG91dHBhdF9zZXR0bGVfd2F5X25hbWU9Is/WvfAiIHByaWNlX2l0ZW1fbG9jYWxfbmFtZT0issq08ta9MSIgcHJpY2VfaXRlbV9sb2NhbF9jb2RlPSIwMDgwMDAyNSIgcHJpY2VfaXRlbV9zdGRfbmFtZT0iwNu8xtT2uLq1xNK908OyxMHPIiBwcmljZV9pdGVtX3N0ZF9jb2RlPSIwMDUzMzMiIGlkPSJjejEzMDc0MDk3IiBjcmVhdGVfdGltZT0iMjAxNS83LzI5IDM6MzA6NDUiIC8+PGl0ZW0gbGFzdF91cGRhdGVfZHRpbWU9IjIwMTUvNy8yOSAyOjAwOjAxIiBvcmdfY29kZT0iMzUwMjExQTEwMDEiIG91dHBhdF9mb3JtX25vPSIyMDE1MDcyODc0MzUiIG91dHBhdF9mZWVfdHlwZV9jb2RlPSIxNSIgb3V0cGF0X2ZlZV90eXBlX25hbWU9IrnSusW30SIgb3V0cGF0X2ZlZV9hbW91bnQ9IjMuMDAiIHBheV93YXlfY29kZT0iOTkiIHBheV93YXlfbmFtZT0ixuTL+yIgb3V0cGF0X3NldHRsZV93YXlfY29kZT0iMDEiIG91dHBhdF9zZXR0bGVfd2F5X25hbWU9Is/WvfAiIHByaWNlX2l0ZW1fbG9jYWxfbmFtZT0iudK6xbfRIiBwcmljZV9pdGVtX2xvY2FsX2NvZGU9Ijk5IiBwcmljZV9pdGVtX3N0ZF9uYW1lPSK50rrFt9EiIHByaWNlX2l0ZW1fc3RkX2NvZGU9Ijk5IiBpZD0iZ2gyMDE1MDcyODc0MzUgICAgOTkiIGNyZWF0ZV90aW1lPSIyMDE1LzcvMjkgMzozMTo0MiIgLz48L2ZlZT48b3BlcmF0aW9uIC8+PC9yb290Pg==
        </Content>
    </Document>
</ProvideAndRegisterDocumentSetRequest>
